#!/usr/bin/env bash
set -Eeuo pipefail

trap 'echo "Deploy failed on line ${LINENO}" >&2' ERR

REPO_URL="${REPO_URL:-https://github.com/Jetvac/service-payment.git}"
BRANCH="${BRANCH:-}"
APP_NAME="${APP_NAME:-service-payment}"
APP_USER="${APP_USER:-servicepay}"
APP_DIR="${APP_DIR:-/opt/service-payment}"
PORT="${PORT:-4077}"
NODE_MAJOR="${NODE_MAJOR:-22}"
DOMAIN="${DOMAIN:-}"
SETUP_NGINX="${SETUP_NGINX:-false}"
ENABLE_SSL="${ENABLE_SSL:-false}"
REQUESTED_HTTPS_PORT="${HTTPS_PORT:-}"
HTTPS_PORT="${HTTPS_PORT:-8443}"
EMAIL="${EMAIL:-}"
ENABLE_UFW="${ENABLE_UFW:-false}"
APP_ENV_FILE="${APP_ENV_FILE:-/etc/${APP_NAME}.env}"
INITIAL_ADMIN_PASSWORD="${INITIAL_ADMIN_PASSWORD:-}"

log() {
  printf '\n==> %s\n' "$*"
}

require_root() {
  if [[ "${EUID}" -ne 0 ]]; then
    exec sudo -E bash "$0" "$@"
  fi
}

install_base_packages() {
  log "Installing base packages"
  apt-get update
  apt-get install -y ca-certificates curl gnupg git openssl sudo build-essential python3
}

load_existing_env() {
  if [[ -f "${APP_ENV_FILE}" ]]; then
    log "Loading existing application settings"
    set -a
    # shellcheck disable=SC1090
    source "${APP_ENV_FILE}"
    set +a
  fi
  if [[ -n "${REQUESTED_HTTPS_PORT}" ]]; then
    HTTPS_PORT="${REQUESTED_HTTPS_PORT}"
  fi
}

node_is_supported() {
  command -v node >/dev/null 2>&1 || return 1
  node -e '
    const [major, minor] = process.versions.node.split(".").map(Number);
    process.exit(major > 22 || (major === 22 && minor >= 12) ? 0 : 1);
  '
}

install_node() {
  if node_is_supported; then
    log "Node.js $(node -v) is already installed"
    return
  fi

  log "Installing Node.js ${NODE_MAJOR}.x"
  curl -fsSL "https://deb.nodesource.com/setup_${NODE_MAJOR}.x" | bash -
  apt-get install -y nodejs
}

ensure_app_user() {
  if id -u "${APP_USER}" >/dev/null 2>&1; then
    log "User ${APP_USER} already exists"
    return
  fi

  log "Creating system user ${APP_USER}"
  useradd --system --create-home --shell /usr/sbin/nologin "${APP_USER}"
}

checkout_repo() {
  log "Checking out ${REPO_URL}"

  if [[ -d "${APP_DIR}/.git" ]]; then
    git config --global --add safe.directory "${APP_DIR}" || true
    git -C "${APP_DIR}" remote set-url origin "${REPO_URL}"
    git -C "${APP_DIR}" fetch --all --prune
    if [[ -n "${BRANCH}" ]]; then
      git -C "${APP_DIR}" checkout "${BRANCH}"
      git -C "${APP_DIR}" pull --ff-only origin "${BRANCH}"
    else
      git -C "${APP_DIR}" pull --ff-only
    fi
    return
  fi

  if [[ -e "${APP_DIR}" ]]; then
    echo "${APP_DIR} exists but is not a git repository" >&2
    exit 1
  fi

  mkdir -p "$(dirname "${APP_DIR}")"
  if [[ -n "${BRANCH}" ]]; then
    git clone --branch "${BRANCH}" "${REPO_URL}" "${APP_DIR}"
  else
    git clone "${REPO_URL}" "${APP_DIR}"
  fi
}

build_app() {
  log "Installing dependencies and building app"
  cd "${APP_DIR}"

  if [[ -f package-lock.json ]]; then
    npm ci --include=dev
  else
    npm install --include=dev
  fi

  npm run build
  npm prune --omit=dev
  mkdir -p "${APP_DIR}/data"
  chown -R "${APP_USER}:${APP_USER}" "${APP_DIR}"
}

random_password() {
  openssl rand -hex 24
}

shell_escape_env_value() {
  local value
  value="$1"
  printf "'%s'" "${value//\'/\'\\\'\'}"
}

public_url() {
  if [[ -z "${DOMAIN}" ]]; then
    printf 'not configured'
  elif [[ "${ENABLE_SSL}" == "true" ]]; then
    printf 'https://%s:%s' "${DOMAIN}" "${HTTPS_PORT}"
  else
    printf 'http://%s' "${DOMAIN}"
  fi
}

validate_public_ports() {
  if [[ "${ENABLE_SSL}" != "true" ]]; then
    return
  fi
  if [[ ! "${HTTPS_PORT}" =~ ^[0-9]+$ ]] || (( HTTPS_PORT < 1 || HTTPS_PORT > 65535 )); then
    echo "HTTPS_PORT must be a number from 1 to 65535" >&2
    exit 1
  fi
  if [[ "${HTTPS_PORT}" == "443" ]]; then
    echo "Port 443 is unavailable on this host; choose another HTTPS_PORT (default: 8443)" >&2
    exit 1
  fi
  if [[ "${HTTPS_PORT}" == "80" || "${HTTPS_PORT}" == "${PORT}" ]]; then
    echo "HTTPS_PORT must differ from ports 80 and ${PORT}" >&2
    exit 1
  fi
}

write_app_env() {
  if [[ -f "${APP_ENV_FILE}" ]]; then
    log "Preserving existing environment ${APP_ENV_FILE}"
    return
  fi
  if [[ -z "${INITIAL_ADMIN_PASSWORD}" ]]; then
    INITIAL_ADMIN_PASSWORD="$(random_password)"
  fi
  log "Writing app environment ${APP_ENV_FILE}"
  mkdir -p "$(dirname "${APP_ENV_FILE}")"
  {
    echo "# Generated by service-payment deploy script"
    echo "NODE_ENV=production"
    echo "PORT=$(shell_escape_env_value "${PORT}")"
    echo "APP_SERVICE_NAME=$(shell_escape_env_value "${APP_NAME}")"
    echo "APP_DATA_DIR=$(shell_escape_env_value "${APP_DIR}/data")"
    echo "INITIAL_ADMIN_PASSWORD=$(shell_escape_env_value "${INITIAL_ADMIN_PASSWORD}")"
    if [[ -n "${DOMAIN}" ]]; then
      echo "PUBLIC_BASE_URL=$(shell_escape_env_value "$(public_url)")"
      echo "HTTPS_PORT=$(shell_escape_env_value "${HTTPS_PORT}")"
    fi
  } >"${APP_ENV_FILE}"
  chmod 640 "${APP_ENV_FILE}"
}

sync_public_env() {
  if [[ -z "${DOMAIN}" || ! -f "${APP_ENV_FILE}" ]]; then
    return
  fi
  local temporary
  temporary="$(mktemp)"
  grep -Ev '^(PUBLIC_BASE_URL|HTTPS_PORT)=' "${APP_ENV_FILE}" >"${temporary}" || true
  {
    cat "${temporary}"
    echo "PUBLIC_BASE_URL=$(shell_escape_env_value "$(public_url)")"
    echo "HTTPS_PORT=$(shell_escape_env_value "${HTTPS_PORT}")"
  } >"${APP_ENV_FILE}"
  rm -f -- "${temporary}"
  chmod 640 "${APP_ENV_FILE}"
}

install_systemd_service() {
  local npm_bin
  npm_bin="$(command -v npm)"

  log "Installing systemd service ${APP_NAME}.service"
  cat >"/etc/systemd/system/${APP_NAME}.service" <<EOF
[Unit]
Description=Service Payment web app
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=${APP_USER}
Group=${APP_USER}
WorkingDirectory=${APP_DIR}
Environment=NODE_ENV=production
Environment=PORT=${PORT}
Environment=APP_SERVICE_NAME=${APP_NAME}
EnvironmentFile=-${APP_ENV_FILE}
ExecStart=${npm_bin} start
Restart=always
RestartSec=5
NoNewPrivileges=true
PrivateTmp=true

[Install]
WantedBy=multi-user.target
EOF

  systemctl daemon-reload
  systemctl enable "${APP_NAME}.service"
  systemctl restart "${APP_NAME}.service"
}

install_restart_sudoers() {
  local systemctl_bin
  systemctl_bin="$(command -v systemctl)"

  log "Allowing ${APP_USER} to restart ${APP_NAME}.service"
  cat >"/etc/sudoers.d/${APP_NAME}-restart" <<EOF
${APP_USER} ALL=(root) NOPASSWD: ${systemctl_bin} restart ${APP_NAME}.service
EOF
  chmod 440 "/etc/sudoers.d/${APP_NAME}-restart"
  visudo -cf "/etc/sudoers.d/${APP_NAME}-restart"
}

install_nginx() {
  if [[ -z "${DOMAIN}" && "${SETUP_NGINX}" != "true" ]]; then
    return
  fi

  log "Installing nginx reverse proxy"
  apt-get install -y nginx
  mkdir -p /var/www/letsencrypt

  local server_name
  server_name="${DOMAIN:-_}"

  cat >"/etc/nginx/sites-available/${APP_NAME}.conf" <<EOF
server {
    listen 80;
    server_name ${server_name};

    client_max_body_size 2048m;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/letsencrypt;
        default_type text/plain;
    }

    location / {
        proxy_pass http://127.0.0.1:${PORT};
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
}
EOF

  ln -sfn "/etc/nginx/sites-available/${APP_NAME}.conf" "/etc/nginx/sites-enabled/${APP_NAME}.conf"
  nginx -t
  systemctl enable nginx
  systemctl reload nginx
}

install_ssl() {
  if [[ "${ENABLE_SSL}" != "true" ]]; then
    return
  fi

  if [[ -z "${DOMAIN}" || -z "${EMAIL}" ]]; then
    echo "ENABLE_SSL=true requires DOMAIN and EMAIL" >&2
    exit 1
  fi

  log "Requesting Let's Encrypt certificate for ${DOMAIN}"
  apt-get install -y certbot
  certbot certonly --webroot \
    --non-interactive \
    --agree-tos \
    --email "${EMAIL}" \
    --webroot-path /var/www/letsencrypt \
    -d "${DOMAIN}"

  log "Configuring HTTPS on port ${HTTPS_PORT}"
  cat >"/etc/nginx/sites-available/${APP_NAME}.conf" <<EOF
server {
    listen 80;
    server_name ${DOMAIN};

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/letsencrypt;
        default_type text/plain;
    }

    location / {
        return 308 https://\$host:${HTTPS_PORT}\$request_uri;
    }
}

server {
    listen ${HTTPS_PORT} ssl;
    server_name ${DOMAIN};

    ssl_certificate /etc/letsencrypt/live/${DOMAIN}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${DOMAIN}/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 1d;

    client_max_body_size 2048m;

    location / {
        proxy_pass http://127.0.0.1:${PORT};
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Port ${HTTPS_PORT};
    }
}
EOF

  mkdir -p /etc/letsencrypt/renewal-hooks/deploy
  cat >"/etc/letsencrypt/renewal-hooks/deploy/${APP_NAME}-reload-nginx" <<EOF
#!/usr/bin/env bash
set -e
nginx -t
systemctl reload nginx
EOF
  chmod 755 "/etc/letsencrypt/renewal-hooks/deploy/${APP_NAME}-reload-nginx"
  nginx -t
  systemctl reload nginx
}

configure_ufw() {
  if [[ "${ENABLE_UFW}" != "true" ]]; then
    return
  fi

  log "Configuring UFW"
  apt-get install -y ufw
  ufw allow OpenSSH
  if [[ -n "${DOMAIN}" || "${SETUP_NGINX}" == "true" ]]; then
    ufw allow 80/tcp
    if [[ "${ENABLE_SSL}" == "true" ]]; then
      ufw allow "${HTTPS_PORT}/tcp"
    fi
  else
    ufw allow "${PORT}/tcp"
  fi
  ufw --force enable
}

print_summary() {
  log "Deployment complete"
  systemctl --no-pager --full status "${APP_NAME}.service" || true

  cat <<EOF

App directory: ${APP_DIR}
Systemd unit:  ${APP_NAME}.service
Env file:      ${APP_ENV_FILE}
Local URL:     http://127.0.0.1:${PORT}
Public URL:    $(public_url)
Initial admin password: ${INITIAL_ADMIN_PASSWORD}

Useful commands:
  sudo systemctl status ${APP_NAME}
  sudo journalctl -u ${APP_NAME} -f
  sudo systemctl restart ${APP_NAME}

EOF
}

main() {
  require_root "$@"
  load_existing_env
  validate_public_ports
  install_base_packages
  install_node
  ensure_app_user
  checkout_repo
  build_app
  write_app_env
  sync_public_env
  install_systemd_service
  install_restart_sudoers
  APP_SERVICE_NAME="${APP_NAME}" bash "${APP_DIR}/scripts/install-update-service.sh"
  install_nginx
  install_ssl
  configure_ufw
  print_summary
}

main "$@"
